import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'
import LeftNav from './defualtLayout/LeftNav'

const inter = Inter({ subsets: ['latin'] })
const leftDistance = 20;
const childrenClass = ` w-full ${' ms-' + leftDistance} ps-4 `

export const metadata: Metadata = {
	title: 'this is a Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
	return (
		<html lang="en" className='dark'>
			<body className={inter.className + ` flex flex-nowrap `}>
				<Providers>
					<LeftNav leftDistance={leftDistance} />
					<div className={childrenClass}>
						{children}
					</div>
				</Providers>
			</body>
		</html>
	)
}
