import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'
import LeftNav from './defualtLayout/LeftNav'

const inter = Inter({ subsets: ['latin'] })
const childrenClass = ` w-full ms-20 ps-4 `

export const metadata: Metadata = {
	title: 'this is a Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
	return (
		<html lang="en" className='dark'>
			<body className={inter.className}>
				<Providers>
					<div className='flex flex-nowrap'>
						<LeftNav />
						<div className={childrenClass}>
							{children}
						</div>
					</div>
				</Providers>
			</body>
		</html>
	)
}
